approot/main/routes.py
from flask import render_template, request, Blueprint
from approot.models import Expense
from approot.expenses.forms import ExpenseForm
from flask_login import current_user, login_required

main = Blueprint('main', __name__)



@main.route("/home")
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    expenses = Expense.query.order_by(Expense.expense_date.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', expenses=expenses)

@main.route("/")
@main.route("/about")
def about():
    page = request.args.get('page', 1, type=int)
    expenses = Expense.query.order_by(Expense.expense_date.desc()).paginate(page=page, per_page=5)
    return render_template('about.html', expenses=expenses)

approot/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from approot import db
from approot.models import Post
from approot.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('post/create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post/post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('post/create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

approot/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort, jsonify, json
from flask_login import login_user, current_user, logout_user, login_required
from approot import db, bcrypt
from approot.models import User, Post, Expense
from approot.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm, UpdateRegistredUsersForm)
from approot.expenses.forms import ExpenseForm
from approot.users.utils import save_picture, send_reset_email
import approot.main.utils
from approot.main.utils import get_symbol

users = Blueprint('users', __name__)

##########################  New Change to allow usage of just one template for tabular views#######################
@users.route("/registeredusers", methods=['GET', 'POST'])
@login_required
def registeredusers():
    if current_user.role != 'Admin':
        flash('Your role does not permit access to this page!', 'danger')
        abort(403)
    form = UpdateRegistredUsersForm()
    displayfields = ['author', 'email', 'role', 'dark_mode_get_symbol', 'theme']
    editfields = [
    {'name':'username'},
    {'name':'email'},
    {'name':'role'},
    {'name':'dark_mode','switch':True},
    {'name':'theme'}
    ]
    columns = [
    {'name':'Username','sortable':"true"},
    {'name':'Email','sortable':"false"},
    {'name':'Role','sortable':"true"},
    {'name':'Dark Mode','sortable':"false"},
    {'name':'Theme','sortable':"false"}]
    rows = []
    users = User.query.order_by(User.username.desc()).all()
    for user in users:
        userdict = {'id':user.id,
        'author':user.username,
        'email':user.email,
        'role':user.role,
        'dark_mode_get_symbol':get_symbol(user.dark_mode),
        'dark_mode':user.dark_mode,
        'username':user.username,
        'theme':user.theme}
        rows.append(userdict)
    row_id=None
    return render_template('tabular_view.html', form=form, \
    columns=columns, rows=rows, fields=displayfields, editfields=editfields, \
    update_route='users.update_user', self_route='users.registeredusers',row_id=row_id, \
    delete_route='users.delete_user', title='Registerd Users')

@users.route("/user/update/<int:row_id>", methods=['GET', 'POST'])
@login_required
def update_user(row_id):
    user = User.query.get_or_404(row_id)

    form = UpdateRegistredUsersForm()
    if form.validate_on_submit():
        try:
            user.username = form.username.data
            user.email = form.email.data
            user.role = form.role.data
            user.dark_mode = form.dark_mode.data
            user.theme = form.theme.data
            db.session.commit()
            flash('User details have been updated!', 'success')
            return redirect(url_for('users.registeredusers'))
        except Exception as e:
            db.session.rollback()
            s = str(e)
            if "user.username" in s:
                flash('This username is already taken. Please chose a different one.', 'danger')
                flash('User details have not been updated', 'warning')
            elif "user.email" in s:
                flash('This email is already registered. Please chose a different one.', 'danger')
                flash('User details have not been updated', 'warning')
            else:
                flash(s, 'warning')
    return redirect(url_for('users.registeredusers', row_id=row_id))

@users.route("/user/delete/<int:row_id>", methods=['POST'])
@login_required
def delete_user(row_id):
    user = User.query.get_or_404(row_id)
    if user.id == current_user.id:
        flash('You cannot delete your own account!', 'danger')
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('User has been deleted!', 'success')
    return redirect(url_for('users.registeredusers'))


###################################################################################################################

@users.route("/registeredtestuser", methods=['GET', 'POST'])
@login_required
def registeredtestuser():
    #page = request.args.get('page', 1, type=int)
    #users = User.query.order_by(User.username.desc()).paginate(page=page, per_page=5)
    users = User.query.order_by(User.username.desc()).all()
    form = UpdateRegistredUsersForm()
    users_data = User.query.order_by(User.username.desc()).all()
    return render_template('user/unused_registeredusers.html', title='Registered Users', form=form, users=users)

@users.route("/testuser/delete/<int:user_id>", methods=['POST'])
@login_required
def delete_testuser(user_id):
    user = User.query.get_or_404(user_id)
    if user.id == current_user.id:
        flash('You cannot delete your own account!', 'danger')
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('User has been deleted!', 'success')
    return redirect(url_for('users.registeredtestusers'))

@users.route("/testuser/update/<int:user_id>", methods=['GET', 'POST'])
@login_required
def update_testuser(user_id):
    user = User.query.get_or_404(user_id)
    #if user.id == current_user.id:
    #    flash('You cannot update your own account!', 'danger')
    #    abort(403)
    form = UpdateRegistredUsersForm()
    if form.validate_on_submit():
        try:
            user.username = form.username.data
            user.email = form.email.data
            user.role = form.role.data
            db.session.commit()
            flash('User details have been updated!', 'success')
            return redirect(url_for('users.registeredtestusers'))
        except Exception as e:
            db.session.rollback()
            s = str(e)
            if "user.username" in s:
                flash('This username is already taken. Please chose a different one.', 'danger')
                flash('User details have not been updated', 'warning')
            elif "user.email" in s:
                flash('This email is already registered. Please chose a different one.', 'danger')
                flash('User details have not been updated', 'warning')
            else:
                flash(s, 'warning')
    return redirect(url_for('users.registeretestdusers', user_id=user_id))


@users.route("/register", methods=['GET', 'POST'])
#@login_required
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, role="Pending")
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('user/register_wtf.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('user/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.about'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.dark_mode = form.dark_mode.data
        current_user.theme = form.theme.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.dark_mode.data = current_user.dark_mode
        form.theme.data = current_user.theme
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('user/account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('post/user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('user/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:

approot/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="mt-3">
<h1>About Page</h1>
<p>
  This app shows the basic usage of Flask framework. It allows creation and deletion of users.
  A user can self register but will require an approval from administrator before the user can have access to database entries.
</p>
<p>
  Once the user has access, (s)he can create a post and enter expenses.
  It demonstrates the usage of <code>jinja2 macros</code>, <code>jinja2 templates</code> that are reusable.
  There is one template called <code>tabular_view.html</code> which can generate the table based on values passed as explained below.
  It also uses three partial templates <code>addModalNew.html</code>, <code>deleteModalNew.html</code> and <code>updateModalNew.html</code>
  which in turn use the values passed to the parent template.

  The python code that renders the <code>tabular_view.html</code> can be seen in the functions <code>expenses</code> in approot/expense/routes.py
  and <code>registeredusers</code> in approot/users/routes.py

  Explained below is the usage:
</p>

Create function:
  <pre>
  @users.route("/registeredusers", methods=['GET', 'POST'])
  @login_required
  def registeredusers():
  </pre>
  Now check that the function can be called or needs to be aborted and then assign the form that template will be using.
  <pre>
      if current_user.role != 'Admin':
          flash('Your role does not permit access to this page!', 'danger')
          abort(403)
      form = UpdateRegistredUsersForm()
  </pre>
  Now declare the fields that you want displayed in a list called displayfield
  <pre>
      displayfields = ['author', 'email', 'role', 'dark_mode_get_symbol', 'theme']
  </pre>
  Then declare the fields that you would want displayed on the modals (update and add modals will both use this list).
  Notice that dark_mode has an additional key 'switch' which allows display of checkbox as a switch rather than a tickbox on the form.
  The 'name' key must correspond to the actual name of the field in the form that will be passed to the template.
  <pre>
    editfields = [
    {'name':'username'},
    {'name':'email'},
    {'name':'role'},
    {'name':'dark_mode','switch':True},
    {'name':'theme'}
    ]
  </pre>
  Now declare the columns you would like displayed in the table. If you want the column to be sortable, pass the value for key 'sortable' as 'true' (all lowercase).
  <pre>
    columns = [
    {'name':'Username','sortable':"true"},
    {'name':'Email','sortable':"false"},
    {'name':'Role','sortable':"true"},
    {'name':'Dark Mode','sortable':"false"},
    {'name':'Theme','sortable':"false"}]
  </pre>
  Write the query to get data from the database table. Now declare a list variable rows which will store this data in dictionary format
  and will be used by the templates.
  <pre>
    users = User.query.order_by(User.username.desc()).all()
    rows = []
    for user in users:
        userdict = {'id':user.id,
        'author':user.username,
        'email':user.email,
        'role':user.role,
        'dark_mode_get_symbol':get_symbol(user.dark_mode),
        'dark_mode':user.dark_mode,
        'username':user.username,
        'theme':user.theme}
        rows.append(userdict)
  </pre>

  declare the row_id variable as 'None'. This is used in the template for displaying error on update modal and will be set and passed by update function separately.
  <pre>
    row_id=None
  </pre>
  Finally render template and pass all the above values like so:
  <pre>
    return render_template('tabular_view.html', form=form, \
    columns=columns, rows=rows, fields=displayfields, editfields=editfields, \
    update_route='users.update_user', self_route='users.registeredusers',row_id=row_id, \
    delete_route='users.delete_user', title='Registerd Users')
  </pre>

Some variables directly passed are as explained below:

<code>update_route</code> - Name of the function to be used to update the data in the update modal form.
<code>self_route</code> - Name of the function to be used to insert the data in the add modal form and clone modal form.
<code>delete_route</code> - Name of the function to be used to delete the data.
<code>title</code> - This is optional but normally should include the title of the page that needs to be displayed.


  Use this explanation to follow the usage in expense function to get a better uderstanding.



  <h2>Further activities to explore:</h2>
  <pre>
    * ~~Create Macro for creating fields~~ - Done
    * ~~Create a grid editable form~~ - Added following functionality on expenses page:
      * ~~Ability to make a row editable using edit button.~~ - Done (For Expense Page)
      * ~~Ability to update using Modal Form.~~ - Done (For User Page)
      * ~~Add "search" box. - Basic Search on expenses table is added but can be improved.~~ Done - Applied [Bootstrap Table](https://bootstrap-table.com/)
      * Add "select" row and "multiple delete" - Explore "bootstrap table" as an option.

    * Modals
      * ~~Creation and submission of forms using Modals.~~ - Done
      * ~~Validation to display in Modals and not take back to the page form.~~ - Done
      * ~~Make the update button disappear for entries created by other users.~~ Done
      * ~~Make modal changes for Users table~~ Done
      * Make modal changes for Posts Table.
      * Clean Up code
    * Creation of subforms - Possibly just a mechanism to add modals. ~~Although need to understand the cascade of deletion using SQLAlchemy.~~ CASCADE Deletion now works. Just needed to ensure the models definition included `cascade='all,delete,delete-orphan'` in the relationship definition.
    </pre>

  <h2>How To?</h2>
<ol>
  <li> Clone this repository on your desktop in the python virtual environment.</li>
  <li>Run following commands to install dependencies:</li>
    <pre>
    pip install --upgrade pip
    pip install gunicorn flask run.py flask-bootstrap flask-mail flask-SQLAlchemy flask-bcrypt flask-table flask-wtf flask-login pillow
    </pre>
  <li> Go to the directory <code>approot</code> on terminal / commandline and give the command <code>python run.py</code></li>
  <li> Install any missing dependencies.</li>
  <li> Once the run.py has worked, press <code>Ctrl+C</code> to stop the server.</li>
  <li> Then type python and in the python interpreter initiate database using the <code>create_admin_user.py</code></li>
  <li> Now start the app by typing <code>python run.py</code></li>
  <li> In your browser type: <a href="http://localhost:5000/"></a> and register a user with your own username and password.</li>
  <li> Login using the username <code>admin@admin.com</code> and password <code>adminpassword</code></li>
  <li> Go to "Registered Users" link and update the user role to <code>Admin</code>.</li>
  <li> Logout and login with user you created in Step 7.</li>
  <li> Go to Registered users and delete the default admin user you created.</li>
  <li> Explore further!!!</li>
</ol>
</div>
{% endblock content %}

approot/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="mt-3">
<h2>Hola! {{ current_user.username }}</h2>
{% if current_user.is_authenticated and current_user.role == 'Pending' %}
<h3> Please contact the administrator to get your role changed as you will not have access to all functionality without the right role assigned. </h3>
{% endif %}
</div>
{% endblock content %}

approot/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
      {% if current_user.is_authenticated %}
        {% if current_user.theme.upper() == "DEFAULT" %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        {% endif %}
        {% if current_user.theme.upper() == "SKETCHY" %}
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/sketchy/bootstrap.min.css">
        {% endif %}
        {% if current_user.theme.upper() == "MINTY" %}
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/minty/bootstrap.min.css">
        {% endif %}
      {% else %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
      {% endif %}
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
      <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.css">
      {% if current_user.is_authenticated and current_user.dark_mode == True%}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
      {% else %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='light_theme_main.css') }}">
      {% endif %}
      <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
      <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>
      <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/extensions/export/bootstrap-table-export.min.js"></script>
      <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
      <script src="https://unpkg.com/tableexport.jquery.plugin/libs/jsPDF/jspdf.min.js"></script>
      <script src="https://unpkg.com/tableexport.jquery.plugin/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
      {% block script %}
      {% endblock %}

      {% if title %}
          <title>Expense Tracking App - {{ title }}</title>
      {% else %}
          <title>Expense Tracking App</title>
      {% endif %}
  </head>
  <body>
      <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/"><i class="fas fa-chart-pie" style="font-size:50px">ET</i></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                {% endif %}

                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>

                {% if current_user.is_authenticated and current_user.role != 'Pending' %}
                  <a class="nav-item nav-link" href="{{ url_for('expenses.expense') }}">Expenses</a>
                {% endif %}

              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                <div class="container">
                <div class="dropdown">
                 <a class="dropdown-toggle" data-toggle="dropdown">Dropdown Example
                 <span class="caret"></span></a>
                 <ul class="dropdown-menu">
                   <li><a href="#">HTML</a></li>
                   <li><a href="#">CSS</a></li>
                   <li><a href="#">JavaScript</a></li>
                 </ul>
               </div>
             </div>
                {% if current_user.is_authenticated and current_user.role != 'Pending' %}
                  <!-- <a class="nav-item nav-link" href="{{ url_for('expenses.new_expense', continue_flag = 'No') }}" title="New Expense"><i class="fas fa-cash-register" style="font-size:30px"></i></a> -->
                  <!-- <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}" title="New Post"><i class="fas fa-pen-nib" style="font-size:30px"></i></a> -->
                {% endif %}

                {% if current_user.is_authenticated %}
                {% if current_user.role == "Admin" %}
                  <a class="nav-item nav-link" href="{{ url_for('users.registeredusers') }}" title="Registered Users"><i class="fas fa-users"style="font-size:30px"></i></a>
                {% endif %}
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}" title="Account"><i class="fas fa-portrait" style="font-size:30px"></i></a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}" title="Logout">
                    <div align="center">
                      <div position="relative"><i class="fas fa-sign-out-alt" style="font-size:30px"></i></div>
                      <div position="relative">{{ current_user.username }} </div>
                    </div>
                  </a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-12 mt-3">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}

            {% block content %}
            {% endblock %}

          </div>
          <!-- <div class="col-md-3 ml-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
               <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  {% if current_user.is_authenticated and current_user.role != 'Pending' %}
                  <li class="list-group-item list-group-item-light"><a href="{{ url_for('expenses.new_expense', continue_flag = 'No') }}">New Expense</a></li>
                  {% endif %}
                   <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div> -->
        </div>
      </main>
  </body>
</html>