approot/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from approot.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')

class UpdateRegistredUsersForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    role = SelectField(u'Role', choices=[('Admin', 'Admin'), ('Regular', 'Regular'), ('Pending', 'Pending')])
    dark_mode = BooleanField('Enable Dark Mode?')
    theme = SelectField(u'Theme', choices=[('Default', 'Default'), ('Sketchy', 'Sketchy'), ('Minty', 'Minty')])


    submit = SubmitField('Update')

class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    dark_mode = BooleanField('Enable Dark Mode?')
    theme = SelectField(u'Theme', choices=[('Default', 'Default'), ('Sketchy', 'Sketchy'), ('Minty', 'Minty')])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')


class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

approot/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort, jsonify, json
from flask_login import login_user, current_user, logout_user, login_required
from approot import db, bcrypt
from approot.models import User, Post, Expense
from approot.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm, UpdateRegistredUsersForm)
from approot.expenses.forms import ExpenseForm
from approot.users.utils import save_picture, send_reset_email
import approot.main.utils
from approot.main.utils import get_symbol

users = Blueprint('users', __name__)

##########################  New Change to allow usage of just one template for tabular views#######################
@users.route("/registeredusers", methods=['GET', 'POST'])
@login_required
def registeredusers():
    if current_user.role != 'Admin':
        flash('Your role does not permit access to this page!', 'danger')
        abort(403)
    form = UpdateRegistredUsersForm()
    displayfields = ['author', 'email', 'role', 'dark_mode_get_symbol', 'theme']
    editfields = [
    {'name':'username'},
    {'name':'email'},
    {'name':'role'},
    {'name':'dark_mode','switch':True},
    {'name':'theme'}
    ]
    columns = [
    {'name':'Username','sortable':"true"},
    {'name':'Email','sortable':"false"},
    {'name':'Role','sortable':"true"},
    {'name':'Dark Mode','sortable':"false"},
    {'name':'Theme','sortable':"false"}]
    rows = []
    users = User.query.order_by(User.username.desc()).all()
    for user in users:
        userdict = {'id':user.id,
        'author':user.username,
        'email':user.email,
        'role':user.role,
        'dark_mode_get_symbol':get_symbol(user.dark_mode),
        'dark_mode':user.dark_mode,
        'username':user.username,
        'theme':user.theme}
        rows.append(userdict)
    row_id=None
    return render_template('tabular_view.html', form=form, \
    columns=columns, rows=rows, fields=displayfields, editfields=editfields, \
    update_route='users.update_user', self_route='users.registeredusers',row_id=row_id, \
    delete_route='users.delete_user', title='Registerd Users')

@users.route("/user/update/<int:row_id>", methods=['GET', 'POST'])
@login_required
def update_user(row_id):
    user = User.query.get_or_404(row_id)

    form = UpdateRegistredUsersForm()
    if form.validate_on_submit():
        try:
            user.username = form.username.data
            user.email = form.email.data
            user.role = form.role.data
            user.dark_mode = form.dark_mode.data
            user.theme = form.theme.data
            db.session.commit()
            flash('User details have been updated!', 'success')
            return redirect(url_for('users.registeredusers'))
        except Exception as e:
            db.session.rollback()
            s = str(e)
            if "user.username" in s:
                flash('This username is already taken. Please chose a different one.', 'danger')
                flash('User details have not been updated', 'warning')
            elif "user.email" in s:
                flash('This email is already registered. Please chose a different one.', 'danger')
                flash('User details have not been updated', 'warning')
            else:
                flash(s, 'warning')
    return redirect(url_for('users.registeredusers', row_id=row_id))

@users.route("/user/delete/<int:row_id>", methods=['POST'])
@login_required
def delete_user(row_id):
    user = User.query.get_or_404(row_id)
    if user.id == current_user.id:
        flash('You cannot delete your own account!', 'danger')
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('User has been deleted!', 'success')
    return redirect(url_for('users.registeredusers'))


###################################################################################################################

@users.route("/registeredtestuser", methods=['GET', 'POST'])
@login_required
def registeredtestuser():
    #page = request.args.get('page', 1, type=int)
    #users = User.query.order_by(User.username.desc()).paginate(page=page, per_page=5)
    users = User.query.order_by(User.username.desc()).all()
    form = UpdateRegistredUsersForm()
    users_data = User.query.order_by(User.username.desc()).all()
    return render_template('user/unused_registeredusers.html', title='Registered Users', form=form, users=users)

@users.route("/testuser/delete/<int:user_id>", methods=['POST'])
@login_required
def delete_testuser(user_id):
    user = User.query.get_or_404(user_id)
    if user.id == current_user.id:
        flash('You cannot delete your own account!', 'danger')
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('User has been deleted!', 'success')
    return redirect(url_for('users.registeredtestusers'))

@users.route("/testuser/update/<int:user_id>", methods=['GET', 'POST'])
@login_required
def update_testuser(user_id):
    user = User.query.get_or_404(user_id)
    #if user.id == current_user.id:
    #    flash('You cannot update your own account!', 'danger')
    #    abort(403)
    form = UpdateRegistredUsersForm()
    if form.validate_on_submit():
        try:
            user.username = form.username.data
            user.email = form.email.data
            user.role = form.role.data
            db.session.commit()
            flash('User details have been updated!', 'success')
            return redirect(url_for('users.registeredtestusers'))
        except Exception as e:
            db.session.rollback()
            s = str(e)
            if "user.username" in s:
                flash('This username is already taken. Please chose a different one.', 'danger')
                flash('User details have not been updated', 'warning')
            elif "user.email" in s:
                flash('This email is already registered. Please chose a different one.', 'danger')
                flash('User details have not been updated', 'warning')
            else:
                flash(s, 'warning')
    return redirect(url_for('users.registeretestdusers', user_id=user_id))


@users.route("/register", methods=['GET', 'POST'])
#@login_required
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, role="Pending")
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('user/register_wtf.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('user/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.about'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.dark_mode = form.dark_mode.data
        current_user.theme = form.theme.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.dark_mode.data = current_user.dark_mode
        form.theme.data = current_user.theme
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('user/account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('post/user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('user/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:

approot/templates/user/account.html
{% extends "layout.html" %}
{% from "util/macros_modifiedNew.html" import form_field_custom with context %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="row">
                  <div class="col-md-6">
                    {{ form_field_custom(form.username,with_label=True) }}
                    {{ form_field_custom(form.email,with_label=True, type="email") }}
                    {{ form_field_custom(form.picture,with_label=True,class="form-control-file") }}
                  </div>
                  <div class="col-md-6">
                    
                       {{ form_field_custom(form.theme, with_label=True, value=current_user.theme) }}
                       {{ form_field_custom(form.dark_mode,switch=True) }}

                  </div>
                </div>
                </div>
              </fieldset>
              <div class="form-group">
                  {{ form.submit(class="btn btn-primary") }}
              </div>
          </form>

    </div>
                <!-- <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div> -->







{% endblock content %}

approot/templates/user/login.html
{% extends "layout.html" %}
{% from "util/macros_modified.html" import form_field_custom with context %}
{% block content %}
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form_field_custom(form.email,with_label=True, type="email") }}
                {{ form_field_custom(form.password,with_label=True, type="password") }}
                <!-- {{ form_field_custom(form.remember) }} -->
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary-rev") }}
                <small class="text-muted ml-2">
                    <strong><a href="{{ url_for('users.reset_request') }}">Forgot Password?</a></strong>
                </small>
            </div>
        </form>
    </div>
     <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
    </div>
    </div>
{% endblock content %}

approot/templates/user/register_wtf.html
{% extends "layout.html" %}
{% from "util/macros_modified.html" import form_field_custom with context %}


{% block content %}
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="content-section mt-3">
      <form method="POST" action="{{ url_for('users.register') }}">
          {{ form.hidden_tag() }}

          <legend class="border-bottom mb-4">Register</legend>
          {{ form_field_custom(form.username,with_label=True) }}
          {{ form_field_custom(form.email,with_label=True) }}
          {{ form_field_custom(form.password,with_label=True) }}
          {{ form_field_custom(form.confirm_password,with_label=True) }}

          <div class="form-group">
              {{ form.submit(class="btn btn-primary-rev") }}
          </div>
      </form>
    </div>
  </div>
</div>



{% endblock content %}

approot/templates/user/registeredusers_tbl.html
{% extends "layout.html" %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
{% endblock %}

{% block content %}
<script type="text/javascript">
$(document).ready(function($)
{
	//ajax row data
	var ajax_data = {{ json_data }}.replace(new RegExp(String.fromCharCode(34) + '.*'), ");
  //ajax_data = ajax_data.replace(new RegExp(String.fromCharCode(34) + '.*'), '');
  /*
	[
		{fname:"Code", lname:"With Mark", email:"mark@codewithmark.com"},
		{fname:"Mary", lname:"Moe", email:"mary@gmail.com"},
		{fname:"John", lname:"Doe", email:"john@yahoo.com"},
		{fname:"Julie", lname:"Dooley", email:"julie@gmail.com"},
	]
*/


	var random_id = function  ()
	{
		var id_num = Math.random().toString(9).substr(2,3);
		var id_str = Math.random().toString(36).substr(2);

		return id_num + id_str;
	}


	//--->create data table > start
	var tbl = '';
	tbl +='<table class="table table-hover">'

		//--->create table header > start
		tbl +='<thead>';
			tbl +='<tr>';
			tbl +='<th>First Name</th>';
			tbl +='<th>Last Name</th>';
			tbl +='<th>Email</th>';
			tbl +='<th>Options</th>';
			tbl +='</tr>';
		tbl +='</thead>';
		//--->create table header > end


		//--->create table body > start
		tbl +='<tbody>';

			//--->create table body rows > start
			$.each(ajax_data, function(index, val)
			{
				//you can replace with your database row id
				var row_id = random_id();

				//loop through ajax row data
				tbl +='<tr row_id="'+row_id+'">';
					tbl +='<td ><div class="row_data" edit_type="click" col_name="fname">'+val['fname']+'</div></td>';
					tbl +='<td ><div class="row_data" edit_type="click" col_name="lname">'+val['lname']+'</div></td>';
					tbl +='<td ><div class="row_data" edit_type="click" col_name="email">'+val['email']+'</div></td>';

					//--->edit options > start
					tbl +='<td>';

						tbl +='<span class="btn_edit" > <a href="#" class="btn btn-link " row_id="'+row_id+'" > Edit</a> </span>';

						//only show this button if edit button is clicked
						tbl +='<span class="btn_save"> <a href="#" class="btn btn-link"  row_id="'+row_id+'"> Save</a> | </span>';
						tbl +='<span class="btn_cancel"> <a href="#" class="btn btn-link" row_id="'+row_id+'"> Cancel</a> | </span>';

					tbl +='</td>';
					//--->edit options > end

				tbl +='</tr>';
			});

			//--->create table body rows > end

		tbl +='</tbody>';
		//--->create table body > end

	tbl +='</table>'
	//--->create data table > end

	//out put table data
	$(document).find('.tbl_user_data').html(tbl);

	$(document).find('.btn_save').hide();
	$(document).find('.btn_cancel').hide();


	//--->make div editable > start
	$(document).on('click', '.row_data', function(event)
	{
		event.preventDefault();

		if($(this).attr('edit_type') == 'button')
		{
			return false;
		}

		//make div editable
		$(this).closest('div').attr('contenteditable', 'true');
		//add bg css
		$(this).addClass('bg-warning').css('padding','5px');

		$(this).focus();
	})
	//--->make div editable > end


	//--->save single field data > start
	$(document).on('focusout', '.row_data', function(event)
	{
		event.preventDefault();

		if($(this).attr('edit_type') == 'button')
		{
			return false;
		}

		var row_id = $(this).closest('tr').attr('row_id');

		var row_div = $(this)
		.removeClass('bg-warning') //add bg css
		.css('padding','')

		var col_name = row_div.attr('col_name');
		var col_val = row_div.html();

		var arr = {};
		arr[col_name] = col_val;

		//use the "arr"	object for your ajax call
		$.extend(arr, {row_id:row_id});

		//out put to show
		$('.post_msg').html( '<pre class="bg-success">'+JSON.stringify(arr, null, 2) +'</pre>');

	})
	//--->save single field data > end


	//--->button > edit > start
	$(document).on('click', '.btn_edit', function(event)
	{
		event.preventDefault();
		var tbl_row = $(this).closest('tr');

		var row_id = tbl_row.attr('row_id');

		tbl_row.find('.btn_save').show();
		tbl_row.find('.btn_cancel').show();

		//hide edit button
		tbl_row.find('.btn_edit').hide();

		//make the whole row editable
		tbl_row.find('.row_data')
		.attr('contenteditable', 'true')
		.attr('edit_type', 'button')
		.addClass('bg-warning')
		.css('padding','3px')

		//--->add the original entry > start
		tbl_row.find('.row_data').each(function(index, val)
		{
			//this will help in case user decided to click on cancel button
			$(this).attr('original_entry', $(this).html());
		});
		//--->add the original entry > end

	});
	//--->button > edit > end


	//--->button > cancel > start
	$(document).on('click', '.btn_cancel', function(event)
	{
		event.preventDefault();

		var tbl_row = $(this).closest('tr');

		var row_id = tbl_row.attr('row_id');

		//hide save and cacel buttons
		tbl_row.find('.btn_save').hide();
		tbl_row.find('.btn_cancel').hide();

		//show edit button
		tbl_row.find('.btn_edit').show();

		//make the whole row editable
		tbl_row.find('.row_data')
		.attr('edit_type', 'click')
		.removeClass('bg-warning')
		.css('padding','')

		tbl_row.find('.row_data').each(function(index, val)
		{
			$(this).html( $(this).attr('original_entry') );
		});
	});
	//--->button > cancel > end


	//--->save whole row entery > start
	$(document).on('click', '.btn_save', function(event)
	{
		event.preventDefault();
		var tbl_row = $(this).closest('tr');

		var row_id = tbl_row.attr('row_id');


		//hide save and cacel buttons
		tbl_row.find('.btn_save').hide();
		tbl_row.find('.btn_cancel').hide();

		//show edit button
		tbl_row.find('.btn_edit').show();


		//make the whole row editable
		tbl_row.find('.row_data')
		.attr('edit_type', 'click')
		.removeClass('bg-warning')
		.css('padding','')

		//--->get row data > start
		var arr = {};
		tbl_row.find('.row_data').each(function(index, val)
		{
			var col_name = $(this).attr('col_name');
			var col_val  =  $(this).html();
			arr[col_name] = col_val;
		});
		//--->get row data > end

		//use the "arr"	object for your ajax call
		$.extend(arr, {row_id:row_id});

		//out put to show
		$('.post_msg').html( '<pre class="bg-success">'+JSON.stringify(arr, null, 2) +'</pre>')


	});
	//--->save whole row entery > end


});
</script>



<div class="panel panel-default">
  <div class="panel-heading"><b> Demo </b> </div>

  <div class="panel-body">

	<div class="tbl_user_data"></div>

  </div>

</div>



<div class="panel panel-default">
  <div class="panel-heading"><b>HTML Table Edits/Upates</b> </div>

  <div class="panel-body">

	<p>All the changes will be displayed below</p>
	<div class="post_msg"> </div>

  </div>
</div>

{% endblock content %}

approot/templates/user/reset_request.html
{% extends "layout.html" %}
{% from "util/macros_modified.html" import form_field_custom with context %}
{% block content %}
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="content-section col-md-6">
      <form method="POST" action="">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Reset Password</legend>
              <div class="form-group">
                {{ form_field_custom(form.email,with_label=True, type="email") }}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-primary") }}
          </div>
      </form>
  </div>
</div>

{% endblock content %}

approot/templates/user/unused_registeredusers.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block script %}

{% endblock %}

{% block content %}
<div class="mt-3">
  <table
  class="table table-hover"
  id="user_table"
  data-toggle="table"
  data-search="true"
  data-show-toggle="true"
  data-show-columns="true"
  data-show-export="true"
  data-pagination="true"
  data-show-extended-pagination="true"
  data-page-list="[3, 5, 10, 25, 50, 100, all]"
  data-page-size="5"
  data-show-export="true"
  >
    <thead>
        <tr>
            <th data-sortable="true">Username</th>
            <th data-sortable="true">Email</th>
            <th data-sortable="true">Role</th>
            <th><div align="center">Update</div></th>
            <th><div align="center">Delete</div></th>
        <tr>
    </thead>
    <tbody>
    {% for user in users %}


            <tr row_id="{{ user.id }}">
                  <td>{{ user.username }}</td>
                  <td>{{ user.email }}</td>
                  <td>{{ user.role }}</td>
                  <!-- <td><a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('users.update_testuser', user_id=user.id) }}">Update</a></td> -->
                  <td>
                    <div  align="center">
                        <button type="button" class="btn btn-info btn-sm m-1" data-toggle="modal" data-target="#updateModal{{ user.id }}"><i class="fas fa-edit"></i></button>
                    </div>
                  </td>

                  <td>
                    <div align="center">
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal{{ user.id }}"><i class="fas fa-trash-alt"></i></button>
                    </div>
                  </td>
              </tr>


      <!-- Update Modal -->
      {% include "user/partials/unused_updateModal.html" %}

      {% if user_id %}
        {% if form.errors %}
          <script>
          $("#updateModal{{ user_id }}").modal('show');
          </script>
        {% endif %}
      {% endif %}
      <!-- Delete Modal -->
      <div class="modal fade" id="deleteModal{{ user.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete User?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('users.delete_testuser', user_id=user.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </tbody>
    </table>
</div>

{% endblock content %}