approot/expenses/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, json)
from flask_login import current_user, login_required
from approot import db
from approot.models import Expense, User
from approot.expenses.forms import ExpenseForm
from approot.main.utils import get_symbol
expenses = Blueprint('expenses', __name__)

########################## New Change to allow usage of just one template for tabular views###############
@expenses.route("/expense", defaults={'continue_flag': 'No'}, methods=['GET', 'POST'])
@expenses.route("/expense/<string:continue_flag>", methods=['GET', 'POST'])
@login_required
def expense(continue_flag):
    #expenses = Expense.query.filter_by(author=current_user).order_by(Expense.expense_date.desc()).all()
    form = ExpenseForm()

    displayfields = ['author', 'description', 'amount', 'expense_date', 'vat_amount', 'Transferrable_val']
    editfields = [
    {'name':'description'},
    {'name':'amount'},
    {'name':'expense_date'},
    {'name':'vat_amount'},
    {'name':'Transferrable', 'switch':False}
    ]

    buttonName = 'Add New Expenses'
    columns = [
    {'name':'Author','sortable':"true"},
    {'name':'Description','sortable':"true"},
    {'name':'Amount','sortable':"true"},
    {'name':'Expense Date','sortable':"true"},
    {'name':'VAT Amount','sortable':"false"},
    {'name':'Transferrable','sortable':"false"}]
    rows = []
    expenses = Expense.query.order_by(Expense.expense_date.desc()).all()
    for expense in expenses:

        #if expense.Transferrable == True:
        #    transferrable_var = u'\u2714'
        #else:
        #    transferrable_var = u'\u2717'
        expensedict = {'id':expense.id, 'author':expense.author.username,
                      'description':expense.description, 'amount':"{:.2f}".format(expense.amount),
                      'expense_date':expense.expense_date.strftime('%Y-%m-%d'),
                      'vat_amount':"{:.2f}".format(expense.vat_amount), 'Transferrable_val':get_symbol(expense.Transferrable),
                      'Transferrable':expense.Transferrable
                      }
        rows.append(expensedict)

    return render_template('tabular_view.html', form=form, columns=columns, rows=rows, \
    fields=displayfields, editfields=editfields, update_route='expenses.update_expense', \
    self_route='expenses.expense', create_route='expenses.new_expense', buttonName=buttonName,\
    delete_route='expenses.delete_expense', continue_flag=continue_flag)

@expenses.route("/expense/new/<string:continue_flag>", methods=['GET','POST'])
@login_required
def new_expense(continue_flag):
    form = ExpenseForm()
    if form.validate_on_submit():
        expense = Expense(description=form.description.data, expense_date=form.expense_date.data,
                        amount=form.amount.data,vat_amount=form.vat_amount.data,Transferrable=form.Transferrable.data, author=current_user)
        db.session.add(expense)
        db.session.commit()
        flash('Your expense has been created!', 'success')
    return redirect(url_for('expenses.expense',continue_flag=continue_flag))


@expenses.route("/expense/update/<int:row_id>", methods=['GET', 'POST'])
@login_required
def update_expense(row_id):
    expense = Expense.query.get_or_404(row_id)
    if expense.author != current_user:
        abort(403)
    form = ExpenseForm()
    if form.validate_on_submit():
        expense.description = form.description.data
        expense.amount = form.amount.data
        expense.expense_date = form.expense_date.data
        expense.vat_amount = form.vat_amount.data
        expense.Transferrable = form.Transferrable.data
        db.session.commit()
        flash('Your expense has been updated!', 'success')
        return redirect(url_for('expenses.expense'))
    return redirect(url_for('expenses.expense', row_id=row_id))

@expenses.route("/expense/delete/<int:row_id>", methods=['POST'])
@login_required
def delete_expense(row_id):
    expense = Expense.query.get_or_404(row_id)
    if expense.author != current_user:
        abort(403)
    db.session.delete(expense)
    db.session.commit()
    flash('Your expense has been deleted!', 'success')
    return redirect(url_for('expenses.expense'))
##########################################################################################################

@expenses.route("/testexpense")
@login_required
def testexpense():
    #page = request.args.get('page', 1, type=int)
    #expenses = Expense.query.order_by(Expense.expense_date.desc()).paginate(page=page, per_page=5)
    expenses = Expense.query.order_by(Expense.expense_date.desc()).all()
    form = ExpenseForm()
        #return redirect(url_for('expenses.expense'))
    return render_template('expense/expense.html', expenses=expenses, form=form)

@expenses.route("/testexpense/new", methods=['POST'])
@login_required
def new_testexpense():
    form = ExpenseForm()
    if form.validate_on_submit():
        expense = Expense(description=form.description.data, expense_date=form.expense_date.data,
                        amount=form.amount.data,vat_amount=form.vat_amount.data,Transferrable=form.Transferrable.data, author=current_user)
        db.session.add(expense)
        db.session.commit()
        flash('Your expense has been created!', 'success')
    return redirect(url_for('expenses.testexpense'))

@expenses.route("/user/testexpenses/<string:username>")
def user_testexpenses(username):
    #page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    form = ExpenseForm()
    expenses = Expense.query.filter_by(author=user)\
        .order_by(Expense.expense_date.desc())\
        .all()
        #.paginate(page=page, per_page=5)
    return render_template('expense/testexpense.html', expenses=expenses, user=user, form=form)

@expenses.route("/testexpense/update/<int:expense_id>", methods=['GET', 'POST'])
@login_required
def update_testexpense(expense_id):
    #page = request.args.get('page', 1, type=int)
    #expenses_from_query = Expense.query.order_by(Expense.expense_date.desc()).paginate(page=page, per_page=5)
    expense = Expense.query.get_or_404(expense_id)
    if expense.author != current_user:
        abort(403)
    form = ExpenseForm()
    if form.validate_on_submit():
        expense.description = form.description.data
        expense.amount = form.amount.data
        expense.expense_date = form.expense_date.data
        expense.vat_amount = form.vat_amount.data
        expense.Transferrable = form.Transferrable.data
        db.session.commit()
        flash('Your expense has been updated!', 'success')
        return redirect(url_for('expenses.expense'))
        """ Commented to see if this will have any negative effect on the flow - I think it won't
    elif request.method == 'GET':
        form.description.data = expense.description
        form.amount.data = expense.amount
        form.expense_date.data = expense.expense_date
        form.vat_amount.data = expense.vat_amount
        form.Transferrable.data = expense.Transferrable """
    #return render_template('expense/expense.html', title='Update Expense',
    #                       form=form, legend='Update Expense')
    #return render_template('expense/expense.html', expenses=expenses_from_query, form=form, expense_id=expense_id)
    return redirect(url_for('expenses.testexpense', expense_id=expense_id))

@expenses.route("/testexpense/delete/<int:expense_id>", methods=['POST'])
@login_required
def delete_testexpense(expense_id):
    expense = Expense.query.get_or_404(expense_id)
    if expense.author != current_user:
        abort(403)
    db.session.delete(expense)
    db.session.commit()
    flash('Your expense has been deleted!', 'success')
    return redirect(url_for('expenses.testexpense'))

approot/main/routes.py
from flask import render_template, request, Blueprint
from approot.models import Expense
from approot.expenses.forms import ExpenseForm
from flask_login import current_user, login_required

main = Blueprint('main', __name__)



@main.route("/home")
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    expenses = Expense.query.order_by(Expense.expense_date.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', expenses=expenses)

@main.route("/")
@main.route("/about")
def about():
    page = request.args.get('page', 1, type=int)
    expenses = Expense.query.order_by(Expense.expense_date.desc()).paginate(page=page, per_page=5)
    return render_template('about.html', expenses=expenses)

approot/templates/expense/create_expense.html
{% extends "layout.html" %}
{% block content %}
<div class="amount-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.amount.label(class="form-control-label") }}
                {% if form.amount.errors %}
                    {{ form.amount(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.amount.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.amount(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.expense_date.label(class="form-control-label") }}
                {% if form.expense_date.errors %}
                    {{ form.expense_date(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.expense_date.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}

                    {{ form.expense_date(class="form-control form-control-lg", type="date") }}

                {% endif %}
            </div>
            <div class="form-group">
                {{ form.vat_amount.label(class="form-control-label") }}
                {% if form.vat_amount.errors %}
                    {{ form.vat_amount(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.vat_amount.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}

                    {{ form.vat_amount(class="form-control form-control-lg") }}

                {% endif %}
            </div>
            <div class="form-group">

                {% if form.Transferrable.errors %}
                    {{ form.Transferrable(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.Transferrable.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.Transferrable(type="checkbox") }}
                {% endif %}
                {{ form.Transferrable.label(class="form-control-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>


{% endblock content %}

approot/templates/expense/create_expense_wtf.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="amount-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ wtf.quick_form(form) }}
    </form>
</div>


{% endblock content %}

approot/templates/expense/expense.html
{% extends "layout.html" %}
{% from "util/macros_modified.html" import form_field_custom with context %}

{% block script %}

{% endblock %}

{% block content %}
<div>
  <div class="row mt-3">
    <div class="col-sm-8">
      <button type="button" class="btn btn-primary btn-sm m-1" data-toggle="modal" data-target="#AddNewModal">Add New Expense</button>
      {% include "expense/partials/addModal.html" %}
    </div>
  </div>

  <table
  class="table table-hover"
  id="expense_tbl"
  style="width: 100%"
  data-toggle="table"
  data-search="true"
  data-show-toggle="true"
  data-show-columns="true"
  data-show-export="true"
  data-pagination="true"
  data-show-extended-pagination="true"
  data-page-list="[3, 5, 10, 25, 50, 100, all]"
  data-page-size="5"
  data-show-export="true">
    <colgroup>
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 40%;">
       <col span="1" style="width: 15%;">
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 15%;">
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 5%;">
    </colgroup>
    <thead>
        <tr>
            <th data-sortable="true">Who?</th>
            <th>Description <font color="red">*</font></th>
            <th data-sortable="true">Amount <font color="red">*</font></th>
            <th data-sortable="true">Expense Date <font color="red">*</font></th>
            <th>VAT Amount</th>
            <th>Transferrable</th>
            <th>Update</th>
            <th>Delete</th>
        <tr>
    </thead>
    <tbody>

     {% for expense in expenses %}

              <tr row_id="{{ expense.id }}">

                  <td style="text-align:center;">
                      <div align="center">
                        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + expense.author.image_file) }}">
                      </div>
                      <div align="center">
                        <!--<div class="article-metadata">-->
                          <a class="mr-2" href="{{ url_for('expenses.user_testexpenses', username=expense.author.username) }}">{{ expense.author.username }}</a>
                        <!--</div>-->
                      </div>
                  </td>
                  <!-- <td>{{ expense.description }}</td> -->
                  <form method="POST" action="{{ url_for('expenses.update_testexpense', expense_id=expense.id) }}">
                    <fieldset class="form-group" style="display:none">
                      {{ form.hidden_tag() }}
                      <!--{% set row_id = expense.id|string %}-->
                      <td>{{ expense.description }}</td>
                      <td>{{ expense.amount }}</td>
                      <td>{{ expense.expense_date.strftime('%Y-%m-%d') }}</td>
                      <td>{{ expense.vat_amount }}</td>
                      <!--<td disabled="disabled" checked="checked"></td>-->
                          {% if expense.Transferrable == False %}
                              <!--{{ form_field_custom(form.Transferrable, disabled="disabled", id="Transferrable"+ row_id) }}-->
                              <td>
                                <input name="btSelectItem" type="checkbox" disabled="disabled">
                              </td>
                          {% else %}
                              <!--{{ form_field_custom(form.Transferrable,checked="checked", onclick="return false;", id="Transferrable"+ row_id) }}-->
                              <td>
                                <input data-index="5" name="btSelectItem" type="checkbox" checked="checked" disabled="disabled">
                              </td>
                          {% endif %}
                      <!--</td>-->


                      {% if current_user.username == expense.author.username %}
                        <td><button type="button" class="btn btn-info btn-sm m-1" data-toggle="modal" data-target="#updateModal{{ expense.id }}"><i class="fas fa-edit"></i></button></td>
                        <!--<td><span><button type="button" class="btn btn-info btn-sm m-1" style="Display:block" id="btn_ed{{ expense.id }}"><i class="fas fa-edit"></i></button>
                        <button type="button" class="btn btn-info btn-sm m-1" style="Display:none" id="btn_cancel{{ expense.id }}"><i class="far fa-window-close"></i></button>
                        </span></td>
                        <td><button type="submit" class="btn btn-primary btn-sm m-1" id="btn_up{{ expense.id }}"><i class="fas fa-save"></i></button></td>-->
                        <td><button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal{{ expense.id }}"><i class="fas fa-trash-alt"></i></button></td>
                      {% endif %}

                    </fieldset>
                  </form>
              </tr>

      <!-- Update Modal Button-->
      {% include "expense/partials/updateModal.html" %}
      {% if expense_id %}
        {% if form.errors %}
          <script>
          $("#updateModal{{ expense_id }}").modal('show');
          </script>
        {% endif %}
      {% endif %}
      <!-- Delete Modal Button-->
      {% include "expense/partials/deleteModal.html" %}

    {% endfor %}
    </tbody>
    </table>


</div>

{% endblock content %}

approot/templates/expense/unused_create_expense.html
{% extends "layout.html" %}
{% block content %}
<div class="amount-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.amount.label(class="form-control-label") }}
                {% if form.amount.errors %}
                    {{ form.amount(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.amount.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.amount(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.expense_date.label(class="form-control-label") }}
                {% if form.expense_date.errors %}
                    {{ form.expense_date(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.expense_date.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}

                    {{ form.expense_date(class="form-control form-control-lg", type="date") }}

                {% endif %}
            </div>
            <div class="form-group">
                {{ form.vat_amount.label(class="form-control-label") }}
                {% if form.vat_amount.errors %}
                    {{ form.vat_amount(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.vat_amount.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}

                    {{ form.vat_amount(class="form-control form-control-lg") }}

                {% endif %}
            </div>
            <div class="form-group">

                {% if form.Transferrable.errors %}
                    {{ form.Transferrable(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.Transferrable.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.Transferrable(type="checkbox") }}
                {% endif %}
                {{ form.Transferrable.label(class="form-control-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>


{% endblock content %}

approot/templates/expense/unused_create_expense_wtf.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="amount-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ wtf.quick_form(form) }}
    </form>
</div>


{% endblock content %}

approot/templates/expense/unused_user_expenses.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Expenses by {{ user.username }} (Total Entries {{ expenses.total }})</h1>
    <div>
      <table class="table">
        <thead>
            <tr>
                <th>Who?</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Expense Date</th>
                <th>VAT Amount</th>
                <th>Transferrable</th>
                <th>Edit</th>
                <th>Delete</th>
            <tr>
        </thead>
        {% for expense in expenses.items %}

              <tbody>
                  <tr>
                      <td style="text-align:center;">
                          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + expense.author.image_file) }}">
                          <div class="media-body">
                            <div class="article-metadata">
                              <a class="mr-2" href="{{ url_for('users.user_expenses', username=expense.author.username) }}">{{ expense.author.username }}</a>
                            </div>
                          </div>
                      </td>
                      <td>{{ expense.description }}</td>
                      <td>{{ expense.amount }}</td>
                      <td>{{ expense.expense_date.strftime('%d-%b-%Y') }}</td>
                      <td>{{ expense.vat_amount }}</td>
                      <td>{{ expense.Transferrable }}</td>
                      <td><a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('expenses.update_expense', expense_id=expense.id) }}">Update</a></td>
                      <td><button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal{{ expense.id }}">Delete</button></td>
                  </tr>
              </tbody>


          <!-- Delete Modal -->
          <div class="modal fade" id="deleteModal{{ expense.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">Delete Expense?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action="{{ url_for('expenses.delete_expense', expense_id=expense.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                  </form>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        </table>
        {% for page_num in expenses.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
            {% if expenses.page == page_num %}
              <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
              <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
          {% else %}
            ...
          {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

approot/templates/expense/user_expenses.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Expenses by {{ user.username }} (Total Entries {{ expenses.total }})</h1>
    <div>
      <table class="table">
        <thead>
            <tr>
                <th>Who?</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Expense Date</th>
                <th>VAT Amount</th>
                <th>Transferrable</th>
                <th>Edit</th>
                <th>Delete</th>
            <tr>
        </thead>
        {% for expense in expenses.items %}

              <tbody>
                  <tr>
                      <td style="text-align:center;">
                          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + expense.author.image_file) }}">
                          <div class="media-body">
                            <div class="article-metadata">
                              <a class="mr-2" href="{{ url_for('users.user_expenses', username=expense.author.username) }}">{{ expense.author.username }}</a>
                            </div>
                          </div>
                      </td>
                      <td>{{ expense.description }}</td>
                      <td>{{ expense.amount }}</td>
                      <td>{{ expense.expense_date.strftime('%d-%b-%Y') }}</td>
                      <td>{{ expense.vat_amount }}</td>
                      <td>{{ expense.Transferrable }}</td>
                      <td><a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('expenses.update_expense', expense_id=expense.id) }}">Update</a></td>
                      <td><button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal{{ expense.id }}">Delete</button></td>
                  </tr>
              </tbody>


          <!-- Delete Modal -->
          <div class="modal fade" id="deleteModal{{ expense.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">Delete Expense?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action="{{ url_for('expenses.delete_expense', expense_id=expense.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                  </form>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        </table>
        {% for page_num in expenses.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
            {% if expenses.page == page_num %}
              <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
              <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
          {% else %}
            ...
          {% endif %}
        {% endfor %}
    </div>
{% endblock content %}